version: "3.8"

services:
  mysql:
    image: bitnami/mysql:8.4
    container_name: piettra_mysql
    restart: always
    environment:
      - MYSQL_DATABASE=piettra_db
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=numsey
      - MYSQL_CHARACTER_SET=utf8mb4
      - MYSQL_COLLATE=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/bitnami/mysql/data
    networks:
      - piettra_network

  minio:
    image: minio/minio:latest
    container_name: piettra_minio
    restart: always
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # API S3
      - "9001:9001" # Console Web
    volumes:
      - minio_data:/data
    networks:
      - piettra_network

volumes:
  mysql_data:
    driver: local
  minio_data:
    driver: local

networks:
  piettra_network:
    driver: bridge
