version: "3.8"

services:
  mysql:
    image: bitnami/mysql:8.4
    container_name: piettra_mysql
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_CHARACTER_SET=${MYSQL_CHARACTER_SET}
      - MYSQL_COLLATE=${MYSQL_COLLATE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/bitnami/mysql/data
    networks:
      - piettra_network

  minio:
    image: minio/minio:latest
    container_name: piettra_minio
    restart: always
    env_file:
      - .env
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # API S3
      - "9001:9001" # Console Web
    volumes:
      - minio_data:/data
    networks:
      - piettra_network

volumes:
  mysql_data:
    driver: local
  minio_data:
    driver: local

networks:
  piettra_network:
    driver: bridge
